prof/config/routes.rb
Rails.application.routes.draw do
   resources :users  
   #resources :admin, only: [:update]
   get 'login', to: 'sessions#new'
   post 'login', to: 'sessions#create'
   get 'welcome', to: 'sessions#welcome'
   root 'sessions#welcome'
   get 'authorized', to: 'sessions#page_requires_login'
   get 'users1/got_profile', to: 'users#got_profile' 
   delete 'sessions/destroy', to: 'sessions#destroy'
   get 'admin', to: 'admin#login'
   post 'admin', to: 'admin#create'
   get 'admin/show', to: 'admin#show' 
   get 'admin/reports', to: 'admin#reports'
   get 'admin/searching', to: 'admin#searching'
   post 'admin/searching', to: 'admin#searching'
   get 'admin/edituser', to: 'admin#edituser'
   patch 'admin/edituser', to: 'admin#update'
   put 'admin/edituser', to: 'admin#update'
   get 'admin/showprofile', to: 'admin#showprofile'
  
   require 'sidekiq/web'
   mount Sidekiq::Web => '/sidekiq'
   require 'sidekiq/cron/web'
end

prof/app/views/admin/edituser.html.erb
<h1>Edit User</h1>
 
<%= form_with(model: @user, local: true, url: { :controller => 'admin', :action => 'update' }) do |form| %>
 
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>}
      </ul>
    </div>
  <% end %>
 <p>
  <%= form.label :ID%><br>
  <%= form.text_field :id%><br>
  <%= form.label :FULL_NAME%><br>
  <%= form.text_field :full_name%><br>
  <%= form.label :USERNAME%><br>
  <%= form.text_field :username%><br>
  <%= form.label :EMAIL_ID%><br>
  <%= form.text_field :email_id%><br>
  <%= form.label :Contact_number%><br>
  <%= form.text_field :phone_number%><br>
  <%= form.label :parent_id%><br>
  <%= form.text_field :parent_id%><br>
  <%= form.label :User_category%><br>
  <%= form.select :user_category, ['buyer','seller','broker']%><br>
    <%= form.label :User_status%><br>
  <%= form.select :user_status, ['inactive','active']%><br>
  <%= form.submit %>
</p>
<%end%>
 
<%= link_to 'Back', admin_searching_path%>

prof/app/views/admin/login.html.erb
<h1>Login Admin</h1>
   <%= form_tag '/admin' do %>
   <%= label_tag :username%>
   <%= text_field_tag :username %>
   <%= label_tag :password%>
   <%= password_field_tag :password%>
   <%= submit_tag "Login"%>
<%end%>
<%= link_to 'Back', welcome_path %>

prof/app/views/admin/searching.html.erb
<h1>Search Users</h1>
<%= form_for 'admin/searching', method: :get do |f| %>
 <p>
  <%= f.label "Search by username/email_id/phone_number" %>
  <%= text_field_tag :q, params[:q] %>
  <%= submit_tag "Go", name: nil %>
 </p>
<% end %>
<% unless @users.nil? %>
  <% if @users.empty? %>
    <h2>No posts found matching your query.</h2>
  <% else %>
    <h2>Search results</h2>
    <table style="width: 0%;">
      <thead>
         <tr>
          <th>Id</th>
           <th>Full Name</th>
           <th>username</th>
           <th>Email</th>
           <th>Phone number</th>
           <th>Category</th>
         
         </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
          	<td><%= user.full_name %></td>
            <td><%= user.username %></td>
            <td><%= user.email_id %></td>
            <td><%= user.phone_number %></td>
             <td><%= user.user_category %></td>
            <td><%= link_to ' Profile ', admin_showprofile_path(:user_id => user.id) %></td>
            <td><%= link_to 'Edit ', admin_edituser_path(:user_id => user.id) %></td>
           
          </tr>
        <% end %>
      <tbody>
    </table>
  <% end %>
<% end %>

prof/app/views/admin/show.html.erb
<%= button_to "Show reports", '/admin/reports', method: :get%>
<%= button_to "Search User", '/admin/searching', method: :get%>
<%= button_to "Create User", '/users/new', method: :get%>

prof/app/views/admin/showprofile.html.erb
<p>
  <strong>Profile id:</strong>
  <%= @user.id %>
</p>
<p>
  <strong>Full name:</strong>
  <%= @user.full_name %>
</p>
 
<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>
 
<p>
  <strong>Email id:</strong>
  <%= @user.email_id %>
</p>
 
<p>
  <strong>Phone_number:</strong>
  <%= @user.phone_number %>
</p>
<p>
  <strong>User category:</strong>
  <%= @user.user_category %>
</p>
<p>
  <strong>Created at:</strong>
  <%= @user.created_at %>
</p>
<p>
  <strong>updated at:</strong>
  <%= @user.updated_at %>
</p>
<p>
  <strong>user status:</strong>
  <%= @user.user_status %>
</p>
<p>
  <strong>Parent id</strong>
  <%= @user.parent_id %>
</p>
<%= link_to 'Back', admin_searching_path %>