prof/config/routes.rb
Rails.application.routes.draw do
   resources :users  
   #resources :admin, only: [:update]
   get 'login', to: 'sessions#new'
   post 'login', to: 'sessions#create'
   get 'welcome', to: 'sessions#welcome'
   root 'sessions#welcome'
   get 'authorized', to: 'sessions#page_requires_login'
   get 'users1/got_profile', to: 'users#got_profile' 
   delete 'sessions/destroy', to: 'sessions#destroy'
   get 'admin', to: 'admin#login'
   post 'admin', to: 'admin#create'
   get 'admin/show', to: 'admin#show' 
   get 'admin/reports', to: 'admin#reports'
   get 'admin/searching', to: 'admin#searching'
   post 'admin/searching', to: 'admin#searching'
   get 'admin/edituser', to: 'admin#edituser'
   patch 'admin/edituser', to: 'admin#update'
   put 'admin/edituser', to: 'admin#update'
   get 'admin/showprofile', to: 'admin#showprofile'
  
   require 'sidekiq/web'
   mount Sidekiq::Web => '/sidekiq'
   require 'sidekiq/cron/web'
end

prof/app/models/user.rb
class User < ApplicationRecord
	has_many :children, class_name: "User", foreign_key: "parent_id" , dependent: :destroy
	belongs_to :parent, class_name: "User", optional: true, foreign_key: "parent_id"
	validates_presence_of :full_name, :username, :email_id, :phone_number
	validates_uniqueness_of :username, :phone_number, :email_id
	validates :phone_number, presence: true,length: {minimum:10, maximum:10}, numericality: { only_integer: true }
	enum status: [:buyer, :seller, :broker]
	has_secure_password
	validate :horizontal_validate, on: [:update, :create]
	validate :vertical_validate, on: [:update, :create]

	def horizontal_validate
		#byebug
		#@user = User.find_by(id: id)
		@user_parent = User.find_by(id: parent_id)
		if @user_parent.children.count >= 4
			errors.add(:horizontal_validate, "Children can't be greater than 4")
		end
	end

	def vertical_validate
		@user = User.find_by(id: id)
		@user_parent = User.find_by(id: parent_id)
		 #@user_parent = @user.parent
      	#@user_parent_parent =  @user_parent.parent
      	#@user_children = @user.children
		#@user_parent_parent = @user_parent.parent
		if @user_parent.present?
			if @user_parent.parent.present?
				if !(@user_parent.parent.parent_id == nil  && @user.children.count == 0)
					errors.add(:grandchild, "Cant add because parent is grandchild")    	
    			end
    		elsif !(@user_parent.parent_id == nil && @user.children.count > 0)
    			errors.add(:parent, "Cant add because user has children and parent both")
    		end
    	else 
			@user.children.each do |d| 
 				 if d.children.present?
 				 			errors.add(:grandparent, "cant add because user is grandparent")
 				 		end
 				 	end
 				 
 		end

	end







	include Elasticsearch::Model
	include Elasticsearch::Model::Callbacks

	after_commit on: [:create] do
		__elasticsearch__.index_document
	end

	after_commit on: [:update] do
		__elasticsearch__.update_document
	end
=begin def self.search(query)
	 __elasticsearch__.search(
	  {
	   query: {
	    multi_match: {
	     query: query,
	     fields: [:username, :email_id, :phone_number]
	    }
	   }
	  }
	 )
  end
=end
		def self.search(query)
		__elasticsearch__.search({
			query: {
				multi_match: {
						fields: [:username, :email_id, :phone_number],
            			query: query,
            			type: "phrase_prefix"
				}
			}
		}
		)
		end

	settings index: { number_of_shards: 1} do
		mapping dynamic: false do
		indexes :username, type: 'keyword'
		indexes :email_id, type: 'keyword'
		indexes :phone_number, type: 'keyword'
		end
		end
	end

=begin
		def self.es_search_result(params)
			field = params[:field]
			query = params[:query]
			data = self.__elasticsearch__.search({
				query: {
					bool: {
						must: [{
							term: {
								"#{field}":"#{query}"
							}
						}]
					}
				}
			}).records
			return data
		end
=end

=begin
		def self.search_record(params)
			return es_search_result(params)
		end

		def as_indexed_json(options={})
			{
				"username" => username,
				"email_id" => email_id,
				"phone_number" => phone_number,
				"created_at" => created_at
			}
		end
			def self.insertion_in_es 
				User.__elasticsearch__.client.indices.create \
				index: User.index_name, body: { settings: User.settings.to_hash, mappings: User.mappings.to_hash }

				User.find_each do |i|
					i.__elasticsearch__.index_document
				end
			end
=end

prof/app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create, :edit]
  
  def new
    
  	 @user = User.new
  end

  def create
   @user = User.new(user_params)
   #@user_parent = @user.parent
   #@user_parent_parent = @user_parent.parent
   #if @user_parent_parent.parent_id == nil && @user_parent.children.count < 4 
   if @user.save 
  else
    render json: {errors: @user.errors, message: "Inputs are not correct" } 
  end
   #session[:user_id] = @user.id
   #redirect_to login_path#'/show'
   #render json: { profile_id: @user.id, 
    #message: "You have successfully signed up" }

  end
   def got_profile
    respond_to do | format |
      format.json {render :json=> current_user}
      format.html 
    end
=begin
    @user=User.find_by(id: params[:id])
    render json:
    {
      id: @user.id,
      username: @user.username,
      full_name: @user.full_name,
      email_id: @user.email_id,
      phone_number: @user.phone_number,
      user_category: @user.user_category
    } 
=end
   end
  #def show
   # render plain: 'show'
   # if logged_in?
     #@user = User.find_by(id: params[:id])

    #end
  #end
  def update
   
    if current_user.update(user_params)
      Rails.cache.write(current_user.id,current_user)
      redirect_to users1_got_profile_path

    end
  end
  def edit
    #render plain: "efb"
    @user = Rails.cache.read(current_user.id)
    if @user == nil
      @user = User.find_by(id: current_user.id)
    end
  end
  def reports
  end
  
 
  private
    def user_params
      params.require(:user).permit(:id, :full_name, :username, :email_id, :phone_number, :password, :parent_id, :user_category)
    end
end

prof/app/helpers/users_helper.rb
module UsersHelper
end

prof/app/views/users/create.html.erb
<h1>Successfully Signed up!!</h1>
 <%= link_to 'Login', login_path %>

<%= link_to 'Back', welcome_path %>

prof/app/views/users/edit.html.erb
<h1>Edit User</h1>
 
<%= form_with(model: @user, local: true) do |form| %>
 
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 <p>
  <%= form.label :Profile_id%><br>
  <%= form.text_field :id%><br>
  <<%= form.label :FULL_NAME%><br>
  <%= form.text_field :full_name%><br>
  <%= form.label :USERNAME%><br>
  <%= form.text_field :username%><br>
  <%= form.label :EMAIL_ID%><br>
  <%= form.text_field :email_id%><br>
  <%= form.label :Contact_number%><br>
  <%= form.text_field :phone_number%><br>
  <%= form.label :User_category%><br>
  <%= form.select :user_category, ['buyer','seller','broker']%><br>
  <%= form.label :password%><br>
  <%= form.password_field :password%><br>
 
  <%= form.submit %>
</p>
<%end%>
 
<%= link_to 'Back', login_path %>

prof/app/views/users/got_profile.html.erb
  <strong>Id :</strong>
  <%= current_user.id %>
</p>
  <strong>Full name:</strong>
  <%= current_user.full_name %>
</p>
 
<p>
  <strong>Username:</strong>
  <%= current_user.username %>
</p>
 
<p>
  <strong>Email id:</strong>
  <%= current_user.email_id %>
</p>
 
<p>
  <strong>Phone_number:</strong>
  <%= current_user.phone_number %>
</p>
<p>
  <strong>User category:</strong>
  <%= current_user.user_category %>
</p>
<p>
  <strong>Created at:</strong>
  <%= current_user.created_at %>
</p>
<p>
  <strong>Updated at:</strong>
  <%= current_user.updated_at %>
</p>
  <strong>Parent id:</strong>
  <%= current_user.parent_id %>
</p>
 <p>
  <strong>User children:</strong>
  <% current_user.children.each do |d| %>
  <%= d.username  %>
  <% end %>
</p>
 

<%= link_to 'edit', edit_user_path(current_user) %>
<%= link_to 'Logout', sessions_destroy_path, method: :delete%>

prof/app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f|%>
  <%= f.label :FULL_NAME%><br>
  <%= f.text_field :full_name%><br>
  <%= f.label :USERNAME%><br>
  <%= f.text_field :username%><br>
  <%= f.label :EMAIL_ID%><br>
  <%= f.text_field :email_id%><br>
  <%= f.label :Contact_number%><br>
  <%= f.text_field :phone_number%><br>
  <%= f.label :User_parent%><br>
  <%= f.text_field :parent_id%><br>
  <%= f.label :User_category%><br>
  <%=f.select :user_category, ['broker','buyer','seller']%><br>
  <%= f.label :password%><br>
  <%= f.password_field :password%><br>
  <%= f.submit %>

<%end%>